export const ROLES = {
  ADMIN: "ADMIN",
  RECRUITER: "RECRUITER",
  INTERVIEWER: "INTERVIEWER",
  CANDIDATE: "CANDIDATE",
};

export const PERMISSIONS = {
  DASHBOARD: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.INTERVIEWER, ROLES.CANDIDATE],

  USERS: [ROLES.ADMIN],

  ROLES: [ROLES.ADMIN],

  CANDIDATES_VIEW: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.INTERVIEWER],
  CANDIDATES_MANAGE: [ROLES.ADMIN, ROLES.RECRUITER],

  JOBS_VIEW: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.INTERVIEWER, ROLES.CANDIDATE],
  JOBS_MANAGE: [ROLES.ADMIN, ROLES.RECRUITER],

  APPLICATIONS_VIEW: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.CANDIDATE],
  APPLICATIONS_MANAGE: [ROLES.ADMIN, ROLES.RECRUITER],

  INTERVIEWS_VIEW: [
    ROLES.ADMIN,
    ROLES.RECRUITER,
    ROLES.INTERVIEWER,
    ROLES.CANDIDATE,
  ],
  INTERVIEWS_MANAGE: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.INTERVIEWER],

  OFFERS_VIEW: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.CANDIDATE],
  OFFERS_MANAGE: [ROLES.ADMIN, ROLES.RECRUITER],
};
