export const ROLES = {
  ADMIN: "ADMIN",
  RECRUITER: "RECRUITER",
  INTERVIEWER: "INTERVIEWER",
  CANDIDATE: "CANDIDATE",
};

export const PERMISSIONS = {
  DASHBOARD: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.INTERVIEWER, ROLES.CANDIDATE],

  USERS: [ROLES.ADMIN],

  ROLES: [ROLES.ADMIN],

  CANDIDATES: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.INTERVIEWER],

  JOBS: [ROLES.ADMIN, ROLES.RECRUITER],

  APPLICATIONS: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.CANDIDATE],

  INTERVIEWS: [
    ROLES.ADMIN,
    ROLES.RECRUITER,
    ROLES.INTERVIEWER,
    ROLES.CANDIDATE,
  ],

  OFFERS: [ROLES.ADMIN, ROLES.RECRUITER, ROLES.CANDIDATE],
};
